name: Deploy Templatized Data Environment

on:
  pull_request:
    types: [closed]
    branches:
      - staging
      - main
  push:
    branches:
      - staging
      - main

jobs:
  deploy_data_environment:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set environment
        id: set_env
        run: |
          TARGET_BRANCH="${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}"
          
          if [[ $TARGET_BRANCH == "staging" ]]; then
            echo "DEPLOY_ENV=staging" >> $GITHUB_ENV
          elif [[ $TARGET_BRANCH == "main" ]]; then
            echo "DEPLOY_ENV=prod" >> $GITHUB_ENV
          else
            echo "Unexpected branch: $TARGET_BRANCH"
            exit 1
          fi

      - name: Decode private key
        run: |
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" | base64 --decode > rsa_key.p8
          chmod 600 rsa_key.p8

      - name: Generate config.toml
        run: |
          echo "[connections.advanced_data_engineering_snowflake]" > config.toml
          echo "account = \"${{ secrets.SNOWFLAKE_ACCOUNT }}\"" >> config.toml
          echo "user = \"${{ secrets.SNOWFLAKE_USER }}\"" >> config.toml
          echo "private_key_path = \"./rsa_key.p8\"" >> config.toml
          echo "database = \"COURSE_REPO\"" >> config.toml
          echo "schema = \"PUBLIC\"" >> config.toml
          echo "role = \"ACCOUNTADMIN\"" >> config.toml
          echo "warehouse = \"COMPUTE_WH\"" >> config.toml
          echo "authenticator = \"snowflake\"" >> config.toml

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: "latest"
          default-config-file-path: "config.toml"

      - name: Fetch latest changes to Snowflake
        run: snow git fetch course_repo.public.advanced_data_engineering_snowflake

      - name: Deploy templates to data environment
        run: |
          echo "Using branch: ${GITHUB_REF_NAME}"
          snow git execute @advanced_data_engineering_snowflake/branches/${GITHUB_REF_NAME}/module-1/hamburg_weather/pipeline/data/ \
          -D "env='${{ env.DEPLOY_ENV }}'" \
          --database=COURSE_REPO \
          --schema=PUBLIC
